### ISSUE TITLE
What will be the default behavior of the package?

### ISSUE THREAD

**Issue by singhs020** [midknight41/cooperate#1]
Hi,

I was trying the package and there is a slight inconsistency while handling the arguments passed for composing an instance.

For example:

if I use the following line of code,

```
cooperate.compose(null, {});
```

It will return following error:-

```
AssertionError: null and undefined are not allowed
```

In other case when I try a different set of code, mentioned below it actually tried to compose and give the below mentioned error.

```
cooperate.compose("test", {});

//Error
Error: overriding the existing property/attribute 'length' is not allowed.
```

Question: What will be the default behavior of the package? Should it only allow the objects to be passed in the compose method?

Note: I have used the RunKit+ to get the error messages.

Regards
Simranjeet Singh

**Comment by midknight41** [comment]
cooperate only supports composing objects so nulls or strings should be errors. I've improved the error handling now. That has shipped with v1.0.0
